### PR TITLE
Proposal: package structure for sqlite packages

### PR DESCRIPTION
**Pull request by natemcmaster**
This is just a draft. Primary question to answer: could this package structure meet the requirements of Microsoft.Data.Sqlite?

cc @bricelam @Eilon @divega

### CODE REVIEW

**Comment by divega** [comment]
I don't know enough to be sure but this seems like it would work. Do we still need the props file in sqlite.native? Probably a silly question but what makes our package different from others that depend on native payloads?

**Comment by natemcmaster** [comment]
> Do we still need the props file in sqlite.native?

For now, yes. NuGet doesn't offer a simple way to handle native libraries for AnyCPU desktop projects. This props file is the same thing as the one in [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/build/net451/Microsoft.Data.Sqlite.props).

>  what makes our package different from others that depend on native payloads?

This issue I created this proposal to solve is the fact that currently Microsoft.Data.Sqlite ships a managed library author by Microsoft and native libraries authored by SQlite.org.

**Comment by bricelam** [comment]
Instead of using MSBuild, we could use NuGet's content files for Full .NET AnyCPU

**Comment by natemcmaster** [comment]
If I understand correctly, content files only work in project.json projects...which mean we would still need MSBuild for csproj/packages.config

**Comment by bricelam** [comment]
Wow, project.json really just created two NuGets (with mismatched feature sets).

**Comment by natemcmaster** [comment]
After thorough discussion with NuGet, it seems like this split package approach is the only thing that will work well for now.

**Pull request closed without merging**
